### ISSUE TITLE
Clarify relationship of roles/auth in model (and WebACL) with Sufia mediated deposit work

### ISSUE THREAD

**Issue by anarchivist** [hybox/models#49]
See [HyBox Aug-Nov 2016 work cycle plan](https://docs.google.com/document/d/1mvmG4En5l7nqYsDsFZ2fuCH1trQEAmrRlKHrGeOsmaw/edit).

Relevant epics: 
- [ ] projecthydra/sufia#2440 - Defining roles and abilities (_Most immediately relevant_)
- [ ] projecthydra/sufia#2441 - Create and populate roles for approval workflows (_Most immediately relevant_)
- [ ] projecthydra/sufia#2452 - Implement object states (_How does state impact what someone can do with an object?_)

Role-specific discussions
- [ ] projecthydra/sufia#2421
- [ ] projecthydra/sufia#2422
- [ ] projecthydra/sufia#2614
- [ ] projecthydra/sufia#2615
- [ ] projecthydra/sufia#2735

**Comment by anarchivist** [comment]
See also [User Roles and Permissions in Hydra-in-a-Box](https://docs.google.com/document/d/1d3_KggC84paVLM0DahUX6MvHGDVE4sM4Uld0Oxs-UHw/edit)
